# cfg/config.yaml

# Global configuration for Copy-Paste Augmentation for YOLOv8

# hands_inhouse:
#   folder: "/home/utkutopcuoglu/Projects/ebis/copy-paste-aug/hands_inhouse"
# hands_public:
#   folder: "/home/utkutopcuoglu/Projects/ebis/copy-paste-aug/hands_public"
# tags:
#   folder: "/home/utkutopcuoglu/Projects/ebis/copy-paste-aug/tags"

augmentation:
  # Visualization settings:
  # visualization_path: "visualizations"  # Path to save augmented images. Uncomment this if you want to save augmented images.
  debug_crops: false             # Set to true if you want to save individual augmented object crops for debugging.

  # Copy-Paste Augmentation Pipelines:
  copy_paste:
    linear_decay: true       # Enable linear decay of augmentation probability.
    max_epochs: 50           # Maximum number of epochs.
    total_samples: 20000      # Number of samples per epoch (total image numbers).
    hands_inhouse:
      folder: "/content/drive/MyDrive/DATASETS/EBİS/CROPS/250116_EBIS_RFID_TAG_DATASET_V10_80_20/hands_inhouse"
      max_paste_objects: 1
      blend: true
      sigma: 1
      max_attempts: 20
      p: 0.0
      class_id: 3
      hand_min_long_edge_ratio: 0.1     # New: object (hand) will use tag ratios.
      hand_max_long_edge_ratio: 0.6
      max_occlude_ratio: 0.3
    hands_public:
      folder: "/content/drive/MyDrive/DATASETS/EBİS/CROPS/hagrid_hand_crops/hands_public"
      max_paste_objects: 2
      blend: true
      sigma: 1
      max_attempts: 20
      p: 0
      class_id: 3
      hand_min_long_edge_ratio: 0.1
      hand_max_long_edge_ratio: 0.6
      max_occlude_ratio: 0.3
    tags:
      folder: "/content/drive/MyDrive/DATASETS/EBİS/CROPS/250116_EBIS_RFID_TAG_DATASET_V10_80_20/tags-good-bad/good"
      max_paste_objects: 3
      blend: true
      sigma: 1
      max_attempts: 20
      p: 0.9
      class_id: 0
      tag_min_long_edge_ratio: 0.05    # New: object (tag) will use hand ratios.
      tag_max_long_edge_ratio: 0.5
      max_occlude_ratio: 0.4

# Crop augmentation pipelines parameters.
# TODO add local light changes to objects during augmentations.
# TODO increase the light augmentations.
crop_augmentations:
  pixel_transforms:
    random_brightness_contrast:
      brightness_limit: [-0.15, 0.3]  # allow for both darker and brighter variations
      contrast_limit: [-0.15, 0.3]
      p: 0.2
    hue_saturation_value:
      hue_shift_limit: [-5, 15]       # subtle hue variations
      sat_shift_limit: [-10, 20]       # subtle saturation changes
      val_shift_limit: [-5, 15]       # subtle brightness (value) adjustments
      p: 0.15
    rgb_shift:
      r_shift_limit: [-5, 10]
      g_shift_limit: [-5, 10]
      b_shift_limit: [-5, 10]
      p: 0.15
    random_gamma:                   # newly added gamma correction for additional light variation
      gamma_limit: [80, 120]
      p: 0.1
    gaussian_blur:
      p: 0.1
    gauss_noise:
      std_range: [0.03, 0.1]
      p: 0.1
    image_compression:
      quality_range: [80, 100]
      p: 0.1
    clahe:
      clip_limit: 2
      tile_grid_size: [8, 8]
      p: 0.1

  spatial_transforms:
    horizontal_flip:
      p: 0.5
    vertical_flip:
      p: 0.5
    rotate_with_expansion:
      limit: [-90, 90]
      border_mode: "BORDER_CONSTANT"
      value: [0, 0, 0, 0]
      mask_value: [0, 0, 0, 0]
      p: 1
    affine:
      translate_percent: [-0.1, 0.1]    # Increased from [-0.0625, 0.0625] for more lateral shift
      scale: [0.8, 1.2]                 # Wider scaling range for more 2D shape alteration
      rotate: [-15, 15]                 # Rotation kept the same as rotate_with_expansion covers rotation
      border_mode: "BORDER_CONSTANT"
      p: 0.5                          # Increased probability to enhance the effect
    perspective:
      scale: [0.1, 0.25]              # Larger scale range for stronger 3D-like warps
      p: 0.8                        # Increased probability to apply perspective changes more often

  random_crop:
    min_crop: 0.8
    p: 0.75

# Debugging specific configuration. Only for debug_augment.py.
debug:
  dataset_yaml: "/home/utkutopcuoglu/Projects/Datasets/person_datasets/person_data.yaml" # Path to the dataset YAML file for visualization.
  num_augmentations: 5000                             # Number of augmented samples to generate per image.
  debug_folder: "debug"                              # Debug folder where augmented images will be saved.